### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by sheerun** [elm-lang/window#1]
Hey, Mind to add example how to use this module in Elm 0.17 application?

**Comment by oldfartdeveloper** [comment]
Hi @sheerun 

I was looking for the same thing and found this:

> https://gist.github.com/adamdicarlo/1e08c9b7aabd778f7b283cbbf6f4f052

Looks like what I need; hope this helps.

**Comment by oldfartdeveloper** [comment]
I added my own example specifically for beginners; maybe you will find it helpful:

https://github.com/oldfartdeveloper/elm-window-example
