### ISSUE TITLE
Suggestion: add resizesWidth

### ISSUE THREAD

**Issue by norpan** [elm-lang/window#2]
Most applications only care about changes in width, and it seems that on iOS devices, resize messages can be triggered when scrolling (even though the window size does not change).

So it would be a help to those that are only interested in the width to have an event that only fires if the width has actually changed.

Otherwise you'd have to check this yourself in the `update` function, and then put a `lazy` with the model on the `view` function to avoid recalculating the virtual DOM.

Or, another solution may be to check the actual width and only trigger events if that changes

See for instance https://github.com/adaptlearning/adapt_framework/commit/415783b7914f77b861fe046622b6365ccfbe6928

**Comment by stevenyap** [comment]
Even if the width is recalculated, it should not trigger a DOM update since the virtual DOM is still the same. Therefore, it should not have much performance impact.

**Comment by norpan** [comment]
It will not trigger a DOM update, but it will recalculate the virtual DOM even if the model is unchanged, which potentially is pretty costly, and these events fire a lot when scrolling.

Maybe adding an extra function is not needed, but having that check in the link I provided could do little harm and much good, I think.
