### ISSUE TITLE
Window.resizes triggered when scrolling on an iphone

### ISSUE THREAD

**Issue by naazy** [elm-lang/window#3]
Window.resizes triggered when scrolling on an iPhone. Window.resizes is a subscription in my project. It is working as expected, except window.resizes appears to be triggered when scrolling up on an iPhone. I'm using an iPhone 6s but have seen similar behaviour on an iPhone X and iPhone 7. Any thoughts on how to resolve this?

**Comment by ksmithbaylor** [comment]
Could this be because the top/bottom bars in mobile Safari expand and collapse as you scroll?

**Comment by evancz** [comment]
The venues at https://elm-lang.org/community can give better help!
