### ISSUE TITLE
Resize on iOS needs 500ms debounce :iphone:

### ISSUE THREAD

**Issue by robert-wallis** [elm-lang/window#6]
On iOS, the resize message needs a 500ms debounce.

https://openradar.appspot.com/radar?id=5040881597939712

Apparently even the slideshow on Apple's page uses it 😞 
https://hackernoon.com/onresize-event-broken-in-mobile-safari-d8469027bf4d

Should everyone get resize messages 500ms late because of Safari?  I don't know, but if anyone asks, this issue now exists.

Personally I am going to implement my own listener and make it 500ms late because WebGL needs to have an updated camera matrix every time the window size changes, otherwise the scene is squished or stretched because iOS is reporting square window sizes during animation, or just plain wrong sizes as if the keyboard was up.

**Comment by robert-wallis** [comment]
Here's my workaround code:

```elm
debounce time task msg =
    Process.sleep time
        |> Task.andThen (\_ -> task)
        |> Task.perform msg

update msg model =
    case msg of
        Resized windowSize ->
            { model | windowSize = windowSize }
                -- iOS Safari is broken, and needs 310ms to give you the real window size
                ! [ debounce 310 Window.size ResizedDebounced ]

        ResizedDebounced windowSize ->
            { model | windowSize = windowSize }
                ! []
```
This updates the model right away for working platforms, and then a second time with correct values on iOS.  The timing of 310ms was chosen because after analyzing video it looks like 303ms when the animation is complete.  So I padded it a little.

**Comment by evancz** [comment]
I think it makes sense to do this sort of thing in Elm for now. Want to be careful adding debounce to things. I know some events need it in almost all cases, but I would rather not rush into a design.
